### ISSUE TITLE
Docker container does not build

### ISSUE THREAD

**Issue by dmonay** [huridocs/trainable-entity-extractor#10]
I'm on MacOS M1, so `make start` defaulted to the Docker setup. It ran fine for a while and then failed on this step:

` => ERROR [pdf-document-layout-analysis 30/30] RUN python src/download_models.py 37.7s`:

The error itself is this:

```
[+] Running 0/1undError: [Errno 2] No such file or directory: '/app/models/layoutlm-base-uncased/.huggingface/.gitignore.lock'
 ⠧ Service pdf-document-layout-analysis  Building                                                                                                                                                              497.7s
failed to solve: process "/bin/sh -c python src/download_models.py" did not complete successfully: exit code: 1
```

The full stack trace is this:

```
 > [pdf-document-layout-analysis 30/30] RUN python src/download_models.py:
0.677 2024-12-25 15:22:10,221 [INFO] Downloading doclaynet model
1.320 2024-12-25 15:22:10,865 [INFO] Downloaded 0%
5.252 2024-12-25 15:22:14,798 [INFO] Downloaded 20%
8.953 2024-12-25 15:22:18,497 [INFO] Downloaded 40%
12.34 2024-12-25 15:22:21,885 [INFO] Downloaded 60%
15.70 2024-12-25 15:22:25,242 [INFO] Downloaded 80%
19.48 2024-12-25 15:22:29,023 [INFO] Downloaded 100%
19.49 2024-12-25 15:22:29,035 [INFO] Embedding model is being downloaded
19.80 /app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py:1194: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
19.80 For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
19.80   warnings.warn(
Fetching 11 files:  27%|██▋       | 3/11 [00:00<00:00, 15.29it/s]
37.11 Traceback (most recent call last):
37.11   File "/app/src/download_models.py", line 64, in <module>
37.11     download_models("doclaynet")
37.11   File "/app/src/download_models.py", line 60, in download_models
37.11     download_embedding_model()
37.11   File "/app/src/download_models.py", line 35, in download_embedding_model
37.11     snapshot_download(repo_id="microsoft/layoutlm-base-uncased", local_dir=model_path, local_dir_use_symlinks=False)
37.11   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
37.11     return fn(*args, **kwargs)
37.11            ^^^^^^^^^^^^^^^^^^^
37.11   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 294, in snapshot_download
37.11     thread_map(
37.11   File "/app/.venv/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
37.12     return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
37.12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
37.12     return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
37.12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/tqdm/std.py", line 1181, in __iter__
37.12     for obj in iterable:
37.12   File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
37.12     yield _result_or_cancel(fs.pop())
37.12           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
37.12     return fut.result(timeout)
37.12            ^^^^^^^^^^^^^^^^^^^
37.12   File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 449, in result
37.12     return self.__get_result()
37.12            ^^^^^^^^^^^^^^^^^^^
37.12   File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
37.12     raise self._exception
37.12   File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
37.12     result = self.fn(*self.args, **self.kwargs)
37.12              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 268, in _inner_hf_hub_download
37.12     return hf_hub_download(
37.12            ^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
37.12     return fn(*args, **kwargs)
37.12            ^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1202, in hf_hub_download
37.12     return _hf_hub_download_to_local_dir(
37.12            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1406, in _hf_hub_download_to_local_dir
37.12     paths = get_local_download_paths(local_dir=local_dir, filename=filename)
37.12             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/_local_folder.py", line 138, in get_local_download_paths
37.12     metadata_path = _huggingface_dir(local_dir) / "download" / f"{sanitized_filename}.metadata"
37.12                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/_local_folder.py", line 223, in _huggingface_dir
37.12     with WeakFileLock(gitignore_lock):
37.12   File "/opt/conda/lib/python3.11/contextlib.py", line 137, in __enter__
37.12     return next(self.gen)
37.12            ^^^^^^^^^^^^^^
37.12   File "/app/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_fixes.py", line 84, in WeakFileLock
37.12     lock.acquire()
37.12   File "/app/.venv/lib/python3.11/site-packages/filelock/_api.py", line 332, in acquire
37.12     self._acquire()
37.12   File "/app/.venv/lib/python3.11/site-packages/filelock/_unix.py", line 42, in _acquire
37.12     fd = os.open(self.lock_file, open_flags, self._context.mode)
```

Would appreciate any guidance in getting this to run!

**Comment by gabriel-piles** [comment]
I'm pretty confused, it could be that this issue is regarding the document-layout-analysis repo: https://github.com/huridocs/pdf-document-layout-analysis?

Please try it again. 

The issue may be due to temporary unavailability of the model's cloud server. Some Mac M1 users are successfully using the document layout analysis service.

Let us know if it continues to fail.

Have a good day.

**Comment by dmonay** [comment]
Ah yes, it's related to the other repo. Apologies, I must have been on the wrong tab when opening the issue. I'll give it another try. 

Closing this issue, will re-open in correct repo if issue persists. 

Thanks!
